"use client";

import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useT } from "@/lib/i18n/provider";
import { supabase } from "@/lib/supabase";

/** Optional two-factor sign-in with an authenticator app (Supabase TOTP). */
export function MfaSetup() {
  const t = useT();
  const [factorId, setFactorId] = useState<string | null>(null);
  const [enabled, setEnabled] = useState(false);
  const [enrolling, setEnrolling] = useState<{ id: string; qr: string } | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    let active = true;
    supabase.auth.mfa.listFactors().then(({ data }) => {
      const verified = data?.totp?.find((f) => f.status === "verified");
      if (active && verified) {
        setFactorId(verified.id);
        setEnabled(true);
      }
    });
    return () => {
      active = false;
    };
  }, []);

  async function start() {
    setBusy(true);
    setError(null);
    const { data, error: enrollError } = await supabase.auth.mfa.enroll({ factorType: "totp" });
    setBusy(false);
    if (enrollError || !data) {
      setError(enrollError?.message ?? t("auth.genericError"));
      return;
    }
    setEnrolling({ id: data.id, qr: data.totp.qr_code });
  }

  async function confirm(event: FormEvent) {
    event.preventDefault();
    if (!enrolling) return;
    setBusy(true);
    setError(null);
    const { error: verifyError } = await supabase.auth.mfa.challengeAndVerify({ factorId: enrolling.id, code: code.trim() });
    setBusy(false);
    if (verifyError) {
      setError(t("security.error"));
      return;
    }
    setFactorId(enrolling.id);
    setEnabled(true);
    setEnrolling(null);
    setCode("");
  }

  async function disable() {
    if (!factorId) return;
    setBusy(true);
    const { error: unenrollError } = await supabase.auth.mfa.unenroll({ factorId });
    setBusy(false);
    if (unenrollError) {
      setError(unenrollError.message);
      return;
    }
    setEnabled(false);
    setFactorId(null);
  }

  return (
    <div className="flex flex-col gap-(--space-sm)">
      {enabled ? (
        <>
          <p className="text-sm text-success-text">{t("security.enabled")}</p>
          <Button type="button" variant="outline" className="w-fit" disabled={busy} onClick={disable}>{t("security.disable")}</Button>
        </>
      ) : enrolling ? (
        <form onSubmit={confirm} className="flex flex-col gap-(--space-sm)">
          <p className="text-sm text-muted-foreground">{t("security.scan")}</p>
          {/* The QR code is a data URL generated by Supabase for this factor. */}
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={enrolling.qr} alt="" className="size-40 rounded-lg bg-white p-2" />
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="mfa-code">{t("security.code")}</Label>
            <Input id="mfa-code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={(e) => setCode(e.target.value)} required />
          </div>
          <Button type="submit" className="w-fit" disabled={busy}>{t("security.confirm")}</Button>
        </form>
      ) : (
        <Button type="button" className="w-fit" disabled={busy} onClick={start}>{t("security.enable")}</Button>
      )}
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
    </div>
  );
}
