"use client";

import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/lib/supabase";

/** Staff sign-in second step: enrol an authenticator app the first time, then enter its code each session. */
export default function AdminMfaPage() {
  const router = useRouter();
  const [state, setState] = useState<"loading" | "enrol" | "challenge">("loading");
  const [factorId, setFactorId] = useState<string | null>(null);
  const [qr, setQr] = useState<string | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    let active = true;
    void (async () => {
      const { data } = await supabase.auth.mfa.listFactors();
      const verified = data?.totp?.find((f) => f.status === "verified");
      if (!active) return;
      if (verified) {
        setFactorId(verified.id);
        setState("challenge");
        return;
      }
      // An unfinished enrolment blocks a new one, so remove leftovers first.
      for (const f of data?.totp ?? []) await supabase.auth.mfa.unenroll({ factorId: f.id });
      const enrolled = await supabase.auth.mfa.enroll({ factorType: "totp" });
      if (!active) return;
      if (enrolled.error || !enrolled.data) {
        setError(enrolled.error?.message ?? "Could not start setup.");
        return;
      }
      setFactorId(enrolled.data.id);
      setQr(enrolled.data.totp.qr_code);
      setState("enrol");
    })();
    return () => {
      active = false;
    };
  }, []);

  async function submit(event: FormEvent) {
    event.preventDefault();
    if (!factorId) return;
    setBusy(true);
    setError(null);
    const { error: verifyError } = await supabase.auth.mfa.challengeAndVerify({ factorId, code: code.trim() });
    setBusy(false);
    if (verifyError) {
      setError("That code was not correct.");
      return;
    }
    router.push("/admin");
    router.refresh();
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-muted/40 p-(--space-sm)">
      <Card className="w-full max-w-sm">
        <CardHeader className="items-center text-center">
          <CardTitle as="h1" className="text-xl">Two-factor sign-in</CardTitle>
          <CardDescription>
            {state === "enrol" ? "Scan this code with an authenticator app, then enter the 6-digit code it shows." : "Enter the 6-digit code from your authenticator app."}
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col gap-(--space-sm)">
          {state === "enrol" && qr && (
            // The QR code is a data URL generated by Supabase for this factor.
            // eslint-disable-next-line @next/next/no-img-element
            <img src={qr} alt="QR code to add BestCar to your authenticator app" className="mx-auto size-44 rounded-lg bg-white p-2" />
          )}
          {state !== "loading" && (
            <form onSubmit={submit} className="flex flex-col gap-(--space-sm)">
              <div className="flex flex-col gap-1.5">
                <Label htmlFor="mfa-code">6-digit code</Label>
                <Input id="mfa-code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={(e) => setCode(e.target.value)} required autoFocus />
              </div>
              {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
              <Button type="submit" disabled={busy}>Continue</Button>
            </form>
          )}
          {state === "loading" && !error && <p className="text-center text-sm text-muted-foreground">Loading...</p>}
          {state === "loading" && error && <p role="alert" className="text-center text-sm text-destructive">{error}</p>}
        </CardContent>
      </Card>
    </div>
  );
}
